export const REQUEST_RECIPES = "REQUEST_RECIPES";
export const RECEIVE_RECIPES = "RECEIVE_RECIPES";
export const RECEIVE_ERROR_RECIPES = "RECEIVE_ERROR_RECIPES";
export const SET_FILTERS_RECIPES = "SET_FILTERS_RECIPES";
